---
title: ""
output:
  html_document:
    code_folding: hide
    theme: united
    toc: yes
    toc_float: yes
    self_contained: false
    lib_dir: qc_report_files
    fig_caption: yes
  pdf_document:
    toc: yes
    toc_depth: 3
    fig_caption: false
  always_allow_html: true
---


```{r eval=TRUE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(fig.cap = NULL)

library(data.table)
library(ggplot2)
library(ggrepel)
library(GGally)
library(umap)
library(FactoMineR)
library(factoextra)
library(corrplot)
library(viridis)
library(ggpubr)
library(Hmisc)
library(plotly)
library(stringr)
library(bit64)

num_files <- expdes[, .N]
run_per_condition <- expdes[, .(countRepMax = .N), by = .(experiment)]
setnames(run_per_condition, "experiment", "condition")

# for fractions, create file name from mqExperiment and Fraction
if (!("file_name" %in% colnames(expdes))){
  expdes$file_name = paste(expdes$experiment, " - ", expdes$Replicate)
}


if (!protein_only){
  mod_pept_int_rep <- merge(
    run_per_condition,
    mod_pept_int[Imputed == 0, .(Repcount = .N), by = .(id, condition)],
    by = c("condition")
  )
  mod_pept_int_rep[, repPC := Repcount/countRepMax]
  mod_pept_id_in_a_cond <- mod_pept_int_rep[repPC >= 0.5, unique(id)]
  mod_pept_int[, Valid := 0L]
  mod_pept_int[id %in% mod_pept_id_in_a_cond, Valid := 1L]
  rm(mod_pept_id_in_a_cond, mod_pept_int_rep)
  
  pept_int_rep <- merge(
    run_per_condition,
    pept_int[Imputed == 0, .(Repcount = .N), by = .(id, condition)],
    by = c("condition")
  )
  pept_int_rep[, repPC := Repcount/countRepMax]
  pept_id_in_a_cond <- pept_int_rep[repPC >= 0.5, unique(id)]
  pept_int[, Valid := 0L]
  pept_int[id %in% pept_id_in_a_cond, Valid := 1L]
  rm(pept_id_in_a_cond, pept_int_rep)
  
}

prot_int_rep <- merge(
  run_per_condition,
  prot_int[Imputed == 0, .(Repcount = .N), by = .(id, condition)],
  by = c("condition")
)
prot_int_rep[, repPC := Repcount/countRepMax]
prot_id_in_a_cond <- prot_int_rep[repPC >= 0.5, unique(id)]
prot_int[, Valid := 0L]
prot_int[id %in% prot_id_in_a_cond, Valid := 1L]
rm(prot_id_in_a_cond, prot_int_rep)


```


```{r, eval=TRUE, warning=FALSE, echo=FALSE, message=FALSE, error=FALSE}
dt <- copy(evidence)

setnames(dt, "experiment", "condition")
dt[is.na(condition), condition := "Library"]
dt[condition == "Library" & is.na(Replicate), Replicate := .GRP, by = .(`raw file`)]


if (!("fraction" %in% colnames(expdes))) {
  dt <- dt[, .(percent = .N), by = .(`missed cleavages`, condition, Replicate, fraction, `raw file`)]
  dt[, Run := str_c(condition, Replicate, fraction, sep = " - ")]
  xlabel = "Condition - Replicate - Fraction"

} else {
  dt <- dt[, .(percent = .N), by = .(`missed cleavages`, condition, Replicate, `raw file`)]
  dt[, Run := str_c(condition, Replicate, sep = " - ")]
  xlabel = "Condition - Replicate"

}
dt[, `missed cleavages` := as.factor(`missed cleavages`)]

p <- ggplot(dt, aes(x = Run, y = percent,  fill=`missed cleavages`, label=Run)) +
  geom_bar(stat="identity", position=position_fill(reverse = TRUE)) +
  theme_minimal() +
  scale_y_continuous("% missed cleavages", labels = scales::percent) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.2),
        panel.grid.major.y = element_blank(),
        panel.border = element_blank(),
        axis.ticks.y = element_blank()
        ) +
  scale_x_discrete(xlabel)




if (all(is.na(dt$`missed cleavages`))) { 
  cat("'missed cleavage' column is empty. Can't estimate digestion efficiency.")
} else{
  if (output_format == "pdf"){
    p
  } else {
    ggplotly(p, tooltip = c("x","y")) %>% config(displayModeBar = T, 
                                                 modeBarButtons = list(list('toImage')),
                                                 displaylogo = F)
  }
}
```